### ISSUE TITLE
How nx and query logs can be checked?

### ISSUE THREAD

**Issue by CHerSun** [klutchell/dnscrypt-proxy-docker#65]
Normally, one can go into docker container shell and check extra logs using `docker exec -it container /bin/sh`. I've tried bash, sh, /bin/bash, /bin/sh - always the same error:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

How can I access the container to check extra logs?

**Comment by CHerSun** [comment]
Ok, looks like I found answer to how to check the logs, but not the answer on why I can't log into container.

To check logs:

Full config folder is mounted, so unless an absolute path is specified for log files - log files will be created inside config folder mounted into container - so one can just check that folder directly.

**Comment by klutchell** [comment]
Hey @CHerSun , this container is distroless and does not contain a shell, or busybox, or any binaries that would be available to exec into. This keeps the image size extremely tiny and reduces the attack surface for vulnerabilities.

As for logging, the only logs are piped to stdout of the container process by default. If you want to enable logging to disk, you'll need to do that with a custom configuration and put the files on a mounted volume.

**Comment by CHerSun** [comment]
I see. Indeed, it takes up the least amount of resources from all images I've tried. Thank you for answer & for the image.
